# Generated by Django 4.2.4 on 2023-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_eventorganizer_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poster', models.URLField()),
                ('livestream_link', models.URLField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20)),
                ('speakers', models.ManyToManyField(related_name='conferences', to='eventapp.speaker')),
            ],
        ),
    ]
