# Generated by Django 4.2.4 on 2023-09-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_alter_conference_location_alter_conference_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
