# Generated by Django 4.2.4 on 2023-09-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_conference_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventorganizer',
            name='email',
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='emails',
            field=models.ManyToManyField(to='eventapp.emailaddress'),
        ),
    ]
