# Generated by Django 4.2.4 on 2023-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0015_alter_conference_livestream_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='livestream_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
