# Generated by Django 4.2.4 on 2023-09-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0016_alter_conference_livestream_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='livestream_link',
            new_name='livestream',
        ),
    ]
