# Generated by Django 4.2.4 on 2023-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0017_rename_livestream_link_conference_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='max_participants',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
