# Generated by Django 4.2.4 on 2023-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0018_webinar_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='max_participants',
            field=models.PositiveIntegerField(default=50, null=True),
        ),
    ]
