# Generated by Django 4.2.4 on 2023-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0019_alter_webinar_max_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='time',
        ),
        migrations.AddField(
            model_name='webinar',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
