# Generated by Django 4.2.4 on 2023-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0024_webinar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
