# Generated by Django 4.2.4 on 2023-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0026_alter_webinar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizer',
            name='emails',
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='emails',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
