# Generated by Django 4.2.4 on 2024-01-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0028_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('start_range', models.IntegerField()),
                ('end_range', models.IntegerField()),
                ('image', models.ImageField(upload_to='service_images/')),
                ('services_provided', models.TextField()),
                ('description', models.TextField()),
                ('locations', models.ManyToManyField(to='eventapp.location')),
            ],
        ),
    ]
