# Generated by Django 4.2.4 on 2024-01-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0031_remove_service_locations_delete_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='end_range',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_range',
        ),
    ]
