# Generated by Django 4.2.4 on 2024-01-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0032_remove_service_end_range_remove_service_start_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
