# Generated by Django 4.2.4 on 2024-01-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0033_service_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='available_dates',
            field=models.ManyToManyField(blank=True, to='eventapp.availabledate'),
        ),
    ]
