# Generated by Django 4.2.4 on 2024-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0034_availabledate_service_available_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledate',
            name='date',
            field=models.DateField(),
        ),
    ]
