# Generated by Django 4.2.4 on 2024-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0036_rename_availabledate_bookeddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
