# Generated by Django 4.2.4 on 2024-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0037_alter_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
