# Generated by Django 4.2.4 on 2024-02-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0040_bookservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
