# Generated by Django 4.2.4 on 2024-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0042_bookservice_org_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
