# Generated by Django 4.2.4 on 2024-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0043_bookservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
