# Generated by Django 4.2.4 on 2024-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0046_alter_bookservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dates_available',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
