# Generated by Django 4.2.4 on 2024-02-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0047_service_dates_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='booked_dates',
        ),
        migrations.DeleteModel(
            name='BookedDate',
        ),
    ]
