# Generated by Django 4.2.4 on 2024-02-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0048_remove_service_booked_dates_delete_bookeddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='dates_available',
            new_name='booked_dates',
        ),
    ]
