# Generated by Django 4.2.4 on 2024-02-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0054_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
