# Generated by Django 4.2.4 on 2024-03-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0058_alter_review_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookservice',
            name='budget',
        ),
    ]
