# Generated by Django 4.2.4 on 2024-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0061_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=100)),
                ('webinar_title', models.CharField(max_length=100)),
                ('certificate_issued_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
