# Generated by Django 4.2.4 on 2024-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0064_webinar_certificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
