# Generated by Django 4.2.4 on 2024-03-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0065_attendee_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.attendee'),
        ),
    ]
