# Generated by Django 4.2.4 on 2024-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0067_questionnaire_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
