# Generated by Django 4.2.4 on 2024-03-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0068_alter_question_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='webinar',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
