# Generated by Django 4.2.4 on 2024-03-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0070_question_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='certificate_status',
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='certificate_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
